### ISSUE TITLE
ndicapi.h not found while installing

### ISSUE THREAD

**Issue by emmeduz** [UCL/scikit-surgerynditracker#36]
Dear all,
I am trying to install the library on Ubuntu 20.04 but I am getting the following error: 
![attached](https://user-images.githubusercontent.com/8161416/121379113-07c14d80-c944-11eb-82b7-7ee6b0043941.png)

I tried to compile and install ndicapi from the source code but, apparently, this is not solving the issue.
Do you have any hint?

Thanks for your work!

**Comment by thompson318** [comment]
@mianasbat is right , scikit-surgerynditracker depends on https://pypi.org/project/ndicapi/ which currently has prebuilt binaries for python 3.6 and 3.7. It looks like you're using 3.8. If you can use python 3.7 that should solve your problems, otherwise I'll try and get binaries built for python 3.8 tomorrow morning GMT.

**Comment by emmeduz** [comment]
I solved installing python3.7.
Thanks for your help!

**Comment by thompson318** [comment]
@emmeduz Thanks for raising this. I think this should work for python38 as well, see #26 . Let us know how you get on. 
Regards.
